#
# (C) Copyright 2015
# Avionic Design GmbH <www.avionic-design.de>
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y	+= ../../nvidia/venice2/as3722_init.o
obj-y	+= ../common/meerkat.o

include $(srctree)/board/nvidia/common/common.mk
